server {
    listen 80;
    server_name _;

    location / {
        return 200 'Hello World Server 1';
        add_header Content-Type text/plain;
    }

    location /health {
        return 200 '{"status":"ok","role":"web-server"}';
        add_header Content-Type application/json;
    }
}
